version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: tinkertools-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tinkertools
      - MONGO_INITDB_ROOT_PASSWORD=tinkertools
      - MONGO_INITDB_ROOT_DATABASE=tinkertools
    volumes:
      - "./data/mongodb:/data/db"
    networks:
      - tinkernet

networks:
  tinkernet:
